version: '3.8'
services:
  # PHP Application
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-php-app
    ports:
      - "8080:80"

  # MySQL Database
  mysql-db:
    image: mysql:5.7
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: recipebook
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
